/** Rules pages linked from Star Wars sheet sections (single owner of the paths). */
export const DOCS = {
    base: '/docs/star-wars-wod-2e/quick-start#2-fill-in-the-basics',
    attributes: '/docs/star-wars-wod-2e/core-rules/attributes-abilities#attributes',
    skills: '/docs/star-wars-wod-2e/core-rules/attributes-abilities#abilities',
    meritsFlaws: '/docs/star-wars-wod-2e/character/merits-flaws',
    virtues: '/docs/star-wars-wod-2e/character/virtues-willpower#the-three-virtues',
    derived: '/docs/star-wars-wod-2e/character/virtues-willpower#derived-stats',
    force: '/docs/star-wars-wod-2e/character/force',
    forcePowers: '/docs/star-wars-wod-2e/character/force#force-powers',
    forceSkills: '/docs/star-wars-wod-2e/character/force#force-skills',
    equipment: '/docs/star-wars-wod-2e/equipment',
    inventory: '/docs/star-wars-wod-2e/equipment#tools-gear',
    weapons: '/docs/star-wars-wod-2e/equipment#weapons',
    armor: '/docs/star-wars-wod-2e/equipment#armor',
    implants: '/docs/star-wars-wod-2e/equipment#cybernetics',
    health: '/docs/star-wars-wod-2e/combat/health-damage-heal#the-health-track',
    experience: '/docs/star-wars-wod-2e/gm/rewards-advancement',
    creatureIdentity: '/docs/star-wars-wod-2e/creatures/mechanics#step-1-species-type-scale-size',
    creatureAbilities: '/docs/star-wars-wod-2e/creatures/mechanics#step-5-abilities',
    creatureMerits: '/docs/star-wars-wod-2e/creatures/mechanics#step-7-merits--flaws',
    creatureCombat: '/docs/star-wars-wod-2e/creatures/mechanics#step-6-combat',
    bestiary: '/docs/star-wars-wod-2e/creatures/bestiary',
    combatScales: '/docs/star-wars-wod-2e/combat/combat-scales',
    combatFlow: '/docs/star-wars-wod-2e/combat/combat-flow',
    vehicleSheet: '/docs/star-wars-wod-2e/vehicles-mechanisms/traits-systems#vehicle-sheet',
    vehicleAttributes:
        '/docs/star-wars-wod-2e/vehicles-mechanisms/traits-systems#vehicle-attributes',
    vehicleWeapons: '/docs/star-wars-wod-2e/vehicles-mechanisms/traits-systems#weapon-systems',
    crewRoles: '/docs/star-wars-wod-2e/vehicles-mechanisms/space-combat#dice-pool-by-crew-role',
    vehicleDamage:
        '/docs/star-wars-wod-2e/vehicles-mechanisms/durability-damage-repair#vehicle-damage-track',
    modifications: '/docs/star-wars-wod-2e/vehicles-mechanisms/modifications',
    vehicleCatalog: '/docs/star-wars-wod-2e/vehicles-mechanisms/vehicles-list',
    fodder: '/docs/star-wars-wod-2e/creatures/mechanics#unnamed-npcs-fodder',
    quickNpcRolls: '/docs/star-wars-wod-2e/creatures/mechanics#quick-npc-rolls',
    encounterTiers: '/docs/star-wars-wod-2e/gm/building-encounters#npc-tiers',
} as const;
