/* Generated once from the book's names; summaries are the project's own words. */

export const HUNTER_ADVANTAGE_ENTRIES = [
    {
        id: 'linguistics',
        name: 'Linguistics',
        type: 'merit',
        polarity: 'positive',
        group: 'linguistics',
        dots: '•–•••••',
        summary: 'One more fluent language per dot, beyond your native tongue and the local one.',
    },
    {
        id: 'illiterate',
        name: 'Illiterate',
        type: 'flaw',
        polarity: 'negative',
        group: 'linguistics',
        dots: '••',
        summary: 'Cannot read or write; Academics and Science stay at 1 at most.',
    },
    {
        id: 'beautiful',
        name: 'Beautiful',
        type: 'merit',
        polarity: 'positive',
        group: 'looks',
        dots: '••',
        summary: 'One extra die on Social pools where looks matter.',
    },
    {
        id: 'stunning',
        name: 'Stunning',
        type: 'merit',
        polarity: 'positive',
        group: 'looks',
        dots: '••••',
        summary: 'Two extra dice on Social pools where looks matter.',
    },
    {
        id: 'ugly',
        name: 'Ugly',
        type: 'flaw',
        polarity: 'negative',
        group: 'looks',
        dots: '•',
        summary: 'One die fewer on Social pools where looks matter.',
    },
    {
        id: 'repulsive',
        name: 'Repulsive',
        type: 'flaw',
        polarity: 'negative',
        group: 'looks',
        dots: '••',
        summary: 'Two dice fewer on Social pools where looks matter.',
    },
    {
        id: 'solo-cooking',
        name: 'Solo Cooking',
        type: 'merit',
        polarity: 'positive',
        group: 'nutritionist',
        dots: '•',
        summary: 'A proper meal before the session heals one extra Superficial Health.',
    },
    {
        id: 'cell-chef',
        name: 'Cell Chef',
        type: 'merit',
        polarity: 'positive',
        group: 'nutritionist',
        dots: '••',
        summary: 'Cooking for the cell heals one extra Superficial Health for everyone present.',
    },
    {
        id: 'living-on-the-edge',
        name: 'Living on the Edge',
        type: 'flaw',
        polarity: 'negative',
        group: 'psychological',
        dots: '••',
        summary:
            'A new risky thrill in reach nags you with a penalty until you try it or the scene ends.',
    },
    {
        id: 'weak-willed',
        name: 'Weak-Willed',
        type: 'flaw',
        polarity: 'negative',
        group: 'psychological',
        dots: '••',
        summary: 'You cannot actively resist powers that sway your mind or emotions.',
    },
    {
        id: 'addiction',
        name: 'Addiction',
        type: 'flaw',
        polarity: 'negative',
        group: 'substance-abuse',
        dots: '•',
        summary: 'One die fewer on most pools after a scene without your substance.',
    },
    {
        id: 'severe-addiction',
        name: 'Severe Addiction',
        type: 'flaw',
        polarity: 'negative',
        group: 'substance-abuse',
        dots: '••',
        summary: 'Two dice fewer on most pools after a scene without your substance.',
    },
    {
        id: 'unseemly-aura',
        name: 'Unseemly Aura',
        type: 'merit',
        polarity: 'positive',
        group: 'supernatural',
        dots: '••',
        summary:
            'Monsters sometimes take you for one of their own, or for something else entirely.',
    },
    {
        id: 'stigmata',
        name: 'Stigmata',
        type: 'flaw',
        polarity: 'negative',
        group: 'supernatural',
        dots: '•',
        summary: 'You bleed from hands, feet, and brow when hurt; noticeable and hard to hide.',
    },
    {
        id: 'crones-curse',
        name: 'Crone’s Curse',
        type: 'flaw',
        polarity: 'negative',
        group: 'supernatural',
        dots: '••',
        summary: 'You look much older than you are and have one Health box fewer.',
    },
    {
        id: 'allies',
        name: 'Allies',
        type: 'background',
        polarity: 'positive',
        group: 'allies',
        dots: '••–••••••',
        summary:
            'People outside the cell who help you; dots buy how capable and how dependable they are.',
    },
    {
        id: 'enemy',
        name: 'Enemy',
        type: 'flaw',
        polarity: 'negative',
        group: 'allies',
        dots: '•–•••',
        summary: 'Someone outside the cell who works against you and shows up when it hurts most.',
    },
    {
        id: 'contacts',
        name: 'Contacts',
        type: 'background',
        polarity: 'positive',
        group: 'contacts',
        dots: '•–•••',
        summary: 'People who can find information or get you things, from cheap to hard to obtain.',
    },
    {
        id: 'fame',
        name: 'Fame',
        type: 'background',
        polarity: 'positive',
        group: 'fame',
        dots: '•–•••••',
        summary:
            'People know your name, from one subculture up to the whole world; hard to stay unnoticed.',
    },
    {
        id: 'infamy',
        name: 'Infamy',
        type: 'flaw',
        polarity: 'negative',
        group: 'fame',
        dots: '••',
        summary: 'Known for something terrible; reactions go badly, and some want you caught.',
    },
    {
        id: 'dark-secret',
        name: 'Dark Secret',
        type: 'flaw',
        polarity: 'negative',
        group: 'fame',
        dots: '•',
        summary: 'A terrible secret few people know, which could still come out.',
    },
    {
        id: 'infamous-partner',
        name: 'Infamous Partner',
        type: 'flaw',
        polarity: 'negative',
        group: 'fame',
        dots: '•',
        summary: 'Someone close to you is notorious, and it rubs off on you.',
    },
    {
        id: 'influence',
        name: 'Influence',
        type: 'background',
        polarity: 'positive',
        group: 'influence',
        dots: '•–•••••',
        summary:
            'Pull over one group or district of the city, weaker elsewhere; using it draws attention.',
    },
    {
        id: 'despised',
        name: 'Despised',
        type: 'flaw',
        polarity: 'negative',
        group: 'influence',
        dots: '••',
        summary: 'One group or district of the city works against you and your cell.',
    },
    {
        id: 'disliked',
        name: 'Disliked',
        type: 'flaw',
        polarity: 'negative',
        group: 'influence',
        dots: '•',
        summary: 'One die fewer on Social tests with city groups that are not openly on your side.',
    },
    {
        id: 'mask',
        name: 'Mask',
        type: 'background',
        polarity: 'positive',
        group: 'mask',
        dots: '•–••',
        summary: 'A false identity that survives background checks, local or national.',
    },
    {
        id: 'zeroed',
        name: 'Zeroed',
        type: 'background',
        polarity: 'positive',
        group: 'mask',
        dots: '•',
        summary: 'Your real records were erased; officially you do not exist. Needs Mask ••.',
    },
    {
        id: 'cobbler',
        name: 'Cobbler',
        type: 'background',
        polarity: 'positive',
        group: 'mask',
        dots: '•',
        summary: 'You can make or source false identities for others. Needs Mask ••.',
    },
    {
        id: 'person-of-interest',
        name: 'Person of Interest',
        type: 'flaw',
        polarity: 'negative',
        group: 'mask',
        dots: '••',
        summary: 'Intelligence databases flag you as a threat; analysts can connect the dots.',
    },
    {
        id: 'serial-error',
        name: 'Serial Error',
        type: 'flaw',
        polarity: 'negative',
        group: 'mask',
        dots: '•',
        summary: 'A records mistake makes any background check on you look alarming.',
    },
    {
        id: 'mentor',
        name: 'Mentor',
        type: 'background',
        polarity: 'positive',
        group: 'mentor',
        dots: '•–•••••',
        summary: 'An experienced hunter or group who advises and covers for you now and then.',
    },
    {
        id: 'adversary',
        name: 'Adversary',
        type: 'flaw',
        polarity: 'negative',
        group: 'mentor',
        dots: '•–•••',
        summary: 'A rival hunter or group who wants you, your cell, or your mentor to fail.',
    },
    {
        id: 'resources',
        name: 'Resources',
        type: 'background',
        polarity: 'positive',
        group: 'resources',
        dots: '•–•••••',
        summary:
            'Money and property, from living paycheck to paycheck to “anything money can buy”.',
    },
    {
        id: 'destitute',
        name: 'Destitute',
        type: 'flaw',
        polarity: 'negative',
        group: 'resources',
        dots: '•',
        summary: 'No money and no home.',
    },
    {
        id: 'retainers',
        name: 'Retainers',
        type: 'background',
        polarity: 'positive',
        group: 'retainers',
        dots: '•–•••',
        summary: 'Loyal helpers, from an eager tag-along to someone who handles problems alone.',
    },
    {
        id: 'stalkers',
        name: 'Stalkers',
        type: 'flaw',
        polarity: 'negative',
        group: 'retainers',
        dots: '•',
        summary: 'People who get too attached to you keep turning up.',
    },
    {
        id: 'safe-house',
        name: 'Safe House',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '•–•••',
        summary:
            'A home that is more secure and private than a bare room; helps spot and resist intruders.',
    },
    {
        id: 'hidden-armory',
        name: 'Hidden Armory',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '• per dot',
        summary: 'A hidden stash of ordinary guns and ammunition in the safe house.',
    },
    {
        id: 'panic-room',
        name: 'Panic Room',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '• per dot',
        summary: 'A locked room to hide people in, or to hold a captive. Not in small safe houses.',
    },
    {
        id: 'watchmen',
        name: 'Watchmen',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '• per dot',
        summary: 'Guards who watch the safe house; they know nothing of the supernatural.',
    },
    {
        id: 'laboratory',
        name: 'Laboratory',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '• per dot',
        summary: 'Extra dice for science or technology work at home. Not in small safe houses.',
    },
    {
        id: 'luxury',
        name: 'Luxury',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '•',
        summary: 'Impressive decor helps Social tests with guests at home.',
    },
    {
        id: 'postern',
        name: 'Postern',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '• per dot',
        summary: 'A hidden way out; extra dice to slip away from watchers nearby.',
    },
    {
        id: 'security-system',
        name: 'Security System',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '• per dot',
        summary: 'Extra dice to keep intruders out or be warned of them.',
    },
    {
        id: 'surgery',
        name: 'Surgery',
        type: 'background',
        polarity: 'positive',
        group: 'safe-house',
        dots: '•',
        summary: 'A field surgery room; extra dice for Medicine at home. Not in small safe houses.',
    },
    {
        id: 'compromised',
        name: 'Compromised',
        type: 'flaw',
        polarity: 'negative',
        group: 'safe-house',
        dots: '••',
        summary: 'The place was raided before and is watched; intruders get extra dice.',
    },
    {
        id: 'creepy',
        name: 'Creepy',
        type: 'flaw',
        polarity: 'negative',
        group: 'safe-house',
        dots: '•',
        summary: 'It looks like a monster’s lair; guests are ill at ease and neighbors talk.',
    },
    {
        id: 'haunted',
        name: 'Haunted',
        type: 'flaw',
        polarity: 'negative',
        group: 'safe-house',
        dots: '• per dot',
        summary: 'Something supernatural lives here that you cannot control or remove.',
    },
    {
        id: 'no-safe-house',
        name: 'No Safe House',
        type: 'flaw',
        polarity: 'negative',
        group: 'safe-house',
        dots: '•',
        summary: 'Nowhere to feel safe: a busy squat, a bad flat, a broken-down trailer.',
    },
    {
        id: 'status',
        name: 'Status',
        type: 'background',
        polarity: 'positive',
        group: 'status',
        dots: '•–•••••',
        summary: 'Standing among the local hunters of one faction, from a known name to a leader.',
    },
    {
        id: 'shunned',
        name: 'Shunned',
        type: 'flaw',
        polarity: 'negative',
        group: 'status',
        dots: '••',
        summary: 'One faction of hunters loathes you and works against you.',
    },
    {
        id: 'suspect',
        name: 'Suspect',
        type: 'flaw',
        polarity: 'negative',
        group: 'status',
        dots: '••',
        summary: 'You broke faith with a faction; Social tests with them are much harder.',
    },
] as const;

export const HUNTER_WEAPON_ENTRIES = [
    {
        id: 'improvised',
        name: 'Improvised weapon',
        kind: 'melee',
        damage: '+0',
        examples: 'A bottle, a chair leg, a wooden stake (stakes matter against vampires).',
    },
    {
        id: 'light-impact',
        name: 'Light impact',
        kind: 'melee',
        damage: '+1',
        examples: 'Brass knuckles, a heavy flashlight.',
    },
    {
        id: 'heavy-impact',
        name: 'Heavy impact',
        kind: 'melee',
        damage: '+2',
        examples: 'A baton, a tire iron, a baseball bat.',
    },
    {
        id: 'light-piercing',
        name: 'Light piercing',
        kind: 'melee',
        damage: '+2',
        examples: 'A switchblade, a crossbow bolt.',
    },
    {
        id: 'light-gunshot',
        name: 'Light gunshot',
        kind: 'ranged',
        damage: '+2',
        examples: 'A small-calibre pistol.',
    },
    {
        id: 'heavy-melee',
        name: 'Heavy melee',
        kind: 'melee',
        damage: '+3',
        examples: 'A sword, a fire axe.',
    },
    {
        id: 'medium-gunshot',
        name: 'Medium gunshot',
        kind: 'ranged',
        damage: '+3',
        examples: 'A service pistol, a hunting rifle, a shotgun at a distance.',
    },
    {
        id: 'heavy-gunshot',
        name: 'Heavy gunshot',
        kind: 'ranged',
        damage: '+4',
        examples: 'A magnum revolver, a shotgun at close range.',
    },
    {
        id: 'huge-melee',
        name: 'Huge melee',
        kind: 'melee',
        damage: '+4',
        examples: 'A two-handed sword, a length of steel beam.',
    },
] as const;

export const HUNTER_ARMOR_ENTRIES = [
    {
        id: 'reinforced-clothing',
        name: 'Reinforced clothing',
        armor: 2,
        note: 'Heavy leathers and the like; no protection against firearms.',
    },
    {
        id: 'ballistic-cloth',
        name: 'Ballistic cloth',
        armor: 2,
        note: 'Protective fabric that passes for ordinary clothes.',
    },
    {
        id: 'kevlar-vest',
        name: 'Kevlar vest',
        armor: 4,
        note: 'A bulletproof vest or flak jacket.',
    },
    {
        id: 'tactical-armor',
        name: 'Tactical armor',
        armor: 6,
        note: 'Police or military gear; one die fewer on Dexterity rolls.',
    },
] as const;

export const HUNTER_GEAR_ENTRIES = [
    {
        id: 'chaoscope',
        name: 'Chaoscope',
        effect: 'Vehicle-mounted scanner: Intelligence + Awareness at Difficulty 6 finds a supernatural threat nearby; easier against a kind already detected.',
    },
    {
        id: 'xscope',
        name: 'XScope',
        effect: 'Tells the living from the dead at a distance by heartbeat, breath, and body heat; some monsters can fool it.',
    },
    {
        id: 'gps-tracker',
        name: 'GPS tracker',
        effect: 'Four extra dice to find whoever carries it; spotting one takes Wits + Streetwise or Technology.',
    },
    {
        id: 'lockpick-gun',
        name: 'Lockpick gun',
        effect: 'Four extra dice to Dexterity + Larceny when picking a lock; hard to explain if found on you.',
    },
    {
        id: 'zip-cuffs',
        name: 'Zip cuffs',
        effect: 'Breaking free takes Strength at Difficulty 5; a blade cuts them easily.',
    },
    {
        id: 'handcuffs',
        name: 'Handcuffs',
        effect: 'Breaking free takes Strength at Difficulty 6, or Dexterity + Larceny at Difficulty 4 to slip out.',
    },
    {
        id: 'tactical-earbuds',
        name: 'Tactical earbuds',
        effect: 'Hearing protection with a cell radio; one extra die to Composure in combat.',
    },
    {
        id: 'disguised-weapon',
        name: 'Disguised weapon',
        effect: 'A weapon that looks like something else; one die fewer to attack unless crafted exceptionally well.',
    },
    {
        id: 'incendiary',
        name: 'Incendiary weapon',
        effect: 'Home-made fire weapons lose one point of damage, but the damage is Aggravated against anything that fears fire.',
    },
] as const;
