import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { format } from 'prettier';

import { flattenUiMessages, loadTranslationSources, type UiMessage } from './translation-source.ts';

const i18nRoot = path.resolve('i18n');
const generatedRoot = path.resolve('src/i18n/generated');

function sortRecord<T>(record: Record<string, T>): Record<string, T> {
    return Object.fromEntries(
        Object.entries(record).sort(([left], [right]) => left.localeCompare(right))
    );
}

async function writeIfChanged(file: string, content: string): Promise<void> {
    await mkdir(path.dirname(file), { recursive: true });
    try {
        if ((await readFile(file, 'utf8')) === content) return;
    } catch {
        // The generated file does not exist yet.
    }
    await writeFile(file, content);
}

async function readCodeCatalog(file: string): Promise<Record<string, UiMessage>> {
    try {
        const parsed = JSON.parse(await readFile(file, 'utf8')) as unknown;
        if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
            throw new Error('must contain a JSON object');
        }
        return parsed as Record<string, UiMessage>;
    } catch (error) {
        if (error instanceof Error && error.message.includes('ENOENT')) return {};
        throw new Error(
            file + ': ' + (error instanceof Error ? error.message : 'could not read JSON'),
            { cause: error }
        );
    }
}

async function formatGeneratedTypeScript(source: string): Promise<string> {
    return format(source, {
        parser: 'typescript',
        semi: true,
        singleQuote: true,
        tabWidth: 4,
        trailingComma: 'es5',
        printWidth: 100,
    });
}

async function buildUiDescriptorModule(englishUi: Record<string, unknown>): Promise<string> {
    const descriptors = createUiDescriptors(englishUi);
    return formatGeneratedTypeScript(
        '// Generated by scripts/build-translations.ts. Do not edit manually.\n\n' +
            'export interface UiMessageDescriptor {\n' +
            '    readonly id: string;\n' +
            '    readonly message: string;\n' +
            '    readonly description?: string;\n' +
            '}\n\n' +
            'export type UiMessageTree = {\n' +
            '    readonly [key: string]: UiMessageTree | UiMessageDescriptor;\n' +
            '};\n\n' +
            'export const uiMessages = ' +
            JSON.stringify(descriptors, null, 4) +
            ' as const satisfies UiMessageTree;\n'
    );
}

function createUiDescriptors(value: unknown, prefix: string[] = []): unknown {
    if (typeof value !== 'object' || value === null || Array.isArray(value)) {
        throw new Error('UI source contains an invalid descriptor at ' + prefix.join('.'));
    }
    if ('message' in value) {
        const entry = value as UiMessage;
        return { id: ['ttgamer', 'ui', ...prefix].join('.'), ...entry };
    }
    return Object.fromEntries(
        Object.entries(value).map(([key, nested]) => [
            key,
            createUiDescriptors(nested, [...prefix, key]),
        ])
    );
}

async function buildCatalogModule(data: Record<string, Record<string, unknown>>): Promise<string> {
    return formatGeneratedTypeScript(
        '// Generated by scripts/build-translations.ts. Do not edit manually.\n\n' +
            'export type CatalogTranslations = Record<string, Record<string, Record<string, Record<string, string>>>>;\n\n' +
            'export const catalogTranslations = ' +
            JSON.stringify(data, null, 4) +
            ' as const satisfies CatalogTranslations;\n'
    );
}

async function main() {
    const sources = await loadTranslationSources();
    for (const locale of sources.locales) {
        const file = path.join(i18nRoot, locale, 'code.json');
        const existing = await readCodeCatalog(file);
        const retained = Object.fromEntries(
            Object.entries(existing).filter(([key]) => !key.startsWith('ttgamer.'))
        );
        const entries = flattenUiMessages(sources.ui[locale], ['ttgamer', 'ui']);
        await writeIfChanged(
            file,
            JSON.stringify(sortRecord({ ...retained, ...entries }), null, 4) + '\n'
        );
    }
    await writeIfChanged(
        path.join(generatedRoot, 'uiMessages.ts'),
        await buildUiDescriptorModule(sources.ui.en)
    );
    await writeIfChanged(
        path.join(generatedRoot, 'catalogTranslations.ts'),
        await buildCatalogModule(sources.data)
    );
    console.log(
        'Built YAML translations for ' +
            sources.locales.join(', ') +
            ': ' +
            sources.counts.en.ui +
            ' UI and ' +
            sources.counts.en.data +
            ' catalog fields.'
    );
}

void main();
