import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { format } from 'prettier';

import {
    CATALOG_LABELS_KEY,
    flattenUiMessages,
    GLOSSARY_ROOT,
    type GlossaryTerm,
    loadGlossary,
    loadTranslationSources,
    TRANSLATION_SOURCE_ROOT,
    type TranslationSources,
    type UiMessage,
} from './translation-source.ts';

export interface TranslationBuildPaths {
    sourceRoot: string;
    glossaryRoot: string;
    i18nRoot: string;
    generatedRoot: string;
}

export const DEFAULT_BUILD_PATHS: TranslationBuildPaths = {
    sourceRoot: TRANSLATION_SOURCE_ROOT,
    glossaryRoot: GLOSSARY_ROOT,
    i18nRoot: path.resolve('i18n'),
    generatedRoot: path.resolve('src/i18n/generated'),
};

export interface TranslationBuild {
    sources: TranslationSources;
    glossary: GlossaryTerm[];
    /** Absolute file path → complete generated content. */
    outputs: Map<string, string>;
}

function sortRecord<T>(record: Record<string, T>): Record<string, T> {
    return Object.fromEntries(
        Object.entries(record).sort(([left], [right]) => left.localeCompare(right))
    );
}

async function readCodeCatalog(file: string): Promise<Record<string, UiMessage>> {
    try {
        const parsed = JSON.parse(await readFile(file, 'utf8')) as unknown;
        if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
            throw new Error('must contain a JSON object');
        }
        return parsed as Record<string, UiMessage>;
    } catch (error) {
        if (error instanceof Error && error.message.includes('ENOENT')) return {};
        throw new Error(
            file + ': ' + (error instanceof Error ? error.message : 'could not read JSON'),
            { cause: error }
        );
    }
}

async function formatGeneratedTypeScript(source: string): Promise<string> {
    return format(source, {
        parser: 'typescript',
        semi: true,
        singleQuote: true,
        tabWidth: 4,
        trailingComma: 'es5',
        printWidth: 100,
    });
}

function createUiDescriptors(value: unknown, prefix: string[] = []): unknown {
    if (typeof value === 'string') {
        return { id: ['ttgamer', 'ui', ...prefix].join('.'), message: value };
    }
    if (typeof value !== 'object' || value === null || Array.isArray(value)) {
        throw new Error('UI source contains an invalid descriptor at ' + prefix.join('.'));
    }
    if ('message' in value) {
        const entry = value as UiMessage;
        return { id: ['ttgamer', 'ui', ...prefix].join('.'), ...entry };
    }
    return Object.fromEntries(
        Object.entries(value).map(([key, nested]) => [
            key,
            createUiDescriptors(nested, [...prefix, key]),
        ])
    );
}

async function buildUiDescriptorModule(englishUi: Record<string, unknown>): Promise<string> {
    return formatGeneratedTypeScript(
        '// Generated by scripts/build-translations.ts. Do not edit manually.\n\n' +
            'export interface UiMessageDescriptor {\n' +
            '    readonly id: string;\n' +
            '    readonly message: string;\n' +
            '    readonly description?: string;\n' +
            '    /** Plural forms separated by `|`; render with usePluralMessage. */\n' +
            '    readonly plural?: boolean;\n' +
            '}\n\n' +
            'export type UiMessageTree = {\n' +
            '    readonly [key: string]: UiMessageTree | UiMessageDescriptor;\n' +
            '};\n\n' +
            'export const uiMessages = ' +
            JSON.stringify(createUiDescriptors(englishUi), null, 4) +
            ' as const satisfies UiMessageTree;\n'
    );
}

async function buildCatalogModule(data: Record<string, Record<string, unknown>>): Promise<string> {
    return formatGeneratedTypeScript(
        '// Generated by scripts/build-translations.ts. Do not edit manually.\n\n' +
            '/** A localized catalog field: text, a list, or nested fields (e.g. `_labels`). */\n' +
            'export type CatalogFieldValue =\n' +
            '    | string\n' +
            '    | readonly string[]\n' +
            '    | { readonly [key: string]: CatalogFieldValue };\n\n' +
            'export type CatalogTranslations = Record<\n' +
            '    string,\n' +
            '    Record<string, Record<string, Readonly<Record<string, CatalogFieldValue>>>>\n' +
            '>;\n\n' +
            'export const catalogTranslations = ' +
            JSON.stringify(data, null, 4) +
            ' as const satisfies CatalogTranslations;\n'
    );
}

/**
 * Catalog data shipped to the browser. English text already lives in the code-owned entries, so
 * the English map keeps only entry names (label references resolve against it); other locales
 * ship every localized field.
 */
function runtimeCatalogData(
    data: Record<string, Record<string, unknown>>
): Record<string, Record<string, unknown>> {
    const english = Object.fromEntries(
        Object.entries(data.en ?? {}).map(([catalogId, catalog]) => [
            catalogId,
            Object.fromEntries(
                Object.entries(catalog as Record<string, unknown>)
                    .filter(([entryId]) => entryId !== CATALOG_LABELS_KEY)
                    .map(([entryId, fields]) => [
                        entryId,
                        { name: (fields as Record<string, unknown>).name },
                    ])
                    .filter(([, fields]) => (fields as { name?: unknown }).name !== undefined)
            ),
        ])
    );
    return { ...data, en: english };
}

/** Runtime map of glossary refs: the English book name and the optional Russian short form. */
async function buildBookTermsModule(glossary: GlossaryTerm[]): Promise<string> {
    const terms: Record<string, { en: string; ruShort?: string }> = {};
    for (const term of glossary) {
        for (const ref of term.refs) {
            terms[ref] = { en: term.en, ...(term.ruShort ? { ruShort: term.ruShort } : {}) };
        }
    }
    return formatGeneratedTypeScript(
        '// Generated by scripts/build-translations.ts from translations/glossary. Do not edit manually.\n\n' +
            'export interface BookTerm {\n' +
            '    /** English book name shown in the hint. */\n' +
            '    readonly en: string;\n' +
            '    /** Approved Russian short form for narrow rows. */\n' +
            '    readonly ruShort?: string;\n' +
            '}\n\n' +
            '/** Glossary refs (`ttgamer.ui.*` or `catalog:<catalogId>/<entryId>`) that are book terms. */\n' +
            'export const bookTerms: Readonly<Record<string, BookTerm>> = ' +
            JSON.stringify(sortRecord(terms), null, 4) +
            ';\n'
    );
}

/** Computes every generated translation file without writing anything. */
export async function buildTranslationOutputs(
    paths: TranslationBuildPaths = DEFAULT_BUILD_PATHS
): Promise<TranslationBuild> {
    const sources = await loadTranslationSources(paths.sourceRoot);
    const glossary = await loadGlossary(paths.glossaryRoot);
    const outputs = new Map<string, string>();
    for (const locale of sources.locales) {
        const file = path.join(paths.i18nRoot, locale, 'code.json');
        const existing = await readCodeCatalog(file);
        const retained = Object.fromEntries(
            Object.entries(existing).filter(([key]) => !key.startsWith('ttgamer.'))
        );
        const entries = Object.fromEntries(
            Object.entries(flattenUiMessages(sources.ui[locale], ['ttgamer', 'ui'])).map(
                // Docusaurus code.json only knows message/description.
                ([key, { message, description }]) => [
                    key,
                    { message, ...(description ? { description } : {}) },
                ]
            )
        );
        outputs.set(file, JSON.stringify(sortRecord({ ...retained, ...entries }), null, 4) + '\n');
    }
    outputs.set(
        path.join(paths.generatedRoot, 'uiMessages.ts'),
        await buildUiDescriptorModule(sources.ui.en)
    );
    outputs.set(
        path.join(paths.generatedRoot, 'catalogTranslations.ts'),
        await buildCatalogModule(runtimeCatalogData(sources.data))
    );
    outputs.set(
        path.join(paths.generatedRoot, 'bookTerms.ts'),
        await buildBookTermsModule(glossary)
    );
    return { sources, glossary, outputs };
}

async function readOrUndefined(file: string): Promise<string | undefined> {
    try {
        return await readFile(file, 'utf8');
    } catch {
        return undefined;
    }
}

/** Files whose generated content differs from what is on disk. */
export async function staleOutputs(outputs: Map<string, string>): Promise<string[]> {
    const stale: string[] = [];
    for (const [file, content] of outputs) {
        if ((await readOrUndefined(file)) !== content) stale.push(file);
    }
    return stale;
}

export async function writeOutputs(outputs: Map<string, string>): Promise<void> {
    for (const file of await staleOutputs(outputs)) {
        await mkdir(path.dirname(file), { recursive: true });
        await writeFile(file, outputs.get(file)!);
    }
}
